apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secrets.yaml
  - v2-config-map.yaml
  - v3-config-map.yaml
  - v4-config-map.yaml
